### ISSUE TITLE
Stack Trace - NPE after corrupted project

### ISSUE THREAD

**Issue by JGillam** [JGillam/burp-paramalyzer#17]
Stack trace happens when running it.  This was after recovering a corrupted project file.  Looks like some additional null checks should be made.

```
java.lang.NullPointerException
	at burp.egf.getProxyHistory(Unknown Source)
	at burp.dqd.getProxyHistory(Unknown Source)
	at burp.bcd.getProxyHistory(Unknown Source)
	at com.professionallyevil.bc.CorrelatorEngine.doInBackground(CorrelatorEngine.java:61)
	at com.professionallyevil.bc.CorrelatorEngine.doInBackground(CorrelatorEngine.java:31)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by JGillam** [comment]
After some conversation with PortSwigger on this, there does not appear to be a way to reproduce or analyze further. As this seems to be a fluke, I will close the issue for now.
