### ISSUE TITLE
Analyze: Execution Exception: java.lang.NoClassDefFoundError: org/json/JSONException

### ISSUE THREAD

**Issue by mr-pmillz** [JGillam/burp-paramalyzer#24]
After clicking the Analyze button, the analysis hangs and throws the following error in the status bar.
```shell
Execution Exception: java.lang.NoClassDefFoundError: org/json/JSONException
```
![image](https://user-images.githubusercontent.com/58376398/185642870-880ec4ba-0347-4d97-88e3-2c1c7193e55b.png)

Here is the stack trace from the paramalyzer extension's Errors tab.

```shell
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/json/JSONException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at com.professionallyevil.paramalyzer.CorrelatorEngine.done(CorrelatorEngine.java:272)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: org/json/JSONException
	at com.professionallyevil.paramalyzer.CorrelatorEngine.processJSON(CorrelatorEngine.java:206)
	at com.professionallyevil.paramalyzer.CorrelatorEngine.parameterFormatAnalysis(CorrelatorEngine.java:178)
	at com.professionallyevil.paramalyzer.CorrelatorEngine.doInBackground(CorrelatorEngine.java:66)
	at com.professionallyevil.paramalyzer.CorrelatorEngine.doInBackground(CorrelatorEngine.java:31)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more
```

**Comment by JGillam** [comment]
@mr-pmillz What version were you running when you saw this?  The BAppStore version or the latest .jar file download (2.2.1 at the time you posted).

**Comment by mr-pmillz** [comment]
Hey @JGillam pardon my late reply, yeah I was running the latest .jar file downloaded from [burp-paramalyzer Releases v2.2.1](https://github.com/JGillam/burp-paramalyzer/releases/tag/v2.2.1) 

Thanks for looking into this! Looks like an awesome extension, can't wait to try it out again!
Cheers 🍻

**Comment by JGillam** [comment]
Cool!  Let me know if you have any other issues or ideas for it.  I usually get a bit of time around the holidays to work on extensions, so now's a good time for feature requests.  :)
